name: Update dependencies

on:
  push:
    branches:
      - master

env:
  GIT_AUTHOR_NAME: GitHub CI
  GIT_AUTHOR_EMAIL: 1198919+mzabaluev@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub CI
  GIT_COMMITTER_EMAIL: 1198919+mzabaluev@users.noreply.github.com

jobs:
  update_deps:
    name: Update baseline Cargo.lock
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ci/cargo-lock
          fetch-depth: 2

      - name: Graft baseline Cargo.lock onto the branch head
        run: |
          git fetch origin ${GITHUB_SHA}
          git rebase FETCH_HEAD
          git reset --soft FETCH_HEAD

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-v1-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-v1-${{ hashFiles('**/Cargo.toml') }}-
            ${{ runner.os }}-cargo-registry-v1-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo update

      - name: Check if Cargo.lock has been modified
        id: deps_updated
        run: |
          test -n "$(git ls-files -m -- Cargo.lock)"
        continue-on-error: true

      - name: Commit Cargo.lock
        if: ${{ steps.deps_updated.outcome == 'success' }}
        run: |
          git add Cargo.lock .gitignore
          git commit -C ORIG_HEAD --reset-author

      - name: Push the rebased Cargo.lock branch
        if: ${{ steps.deps_updated.outcome == 'success' }}
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ci/cargo-lock
          force: true
